# Core Wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Toolkit Backends
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# App fixes (Firefox and Electron applications)
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# UI Consistency
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
